import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'react-loading-skeleton/dist/skeleton.css'
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Quiz App",
  description: "Quiz application generated by Mahdi Mahmoudi",
};

const vazirFont = localFont({
  src: "./fonts/vazir/Vazir.woff2",
});

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vazirFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
